# Generated by Django 5.0 on 2024-01-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile_app", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="subscribe_to_notifications",
            field=models.BooleanField(default=False),
        ),
    ]
