# Generated by Django 5.0 on 2024-01-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile_app", "0005_customuser_subscribe_to_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
